apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-performance-api
  namespace: mlops
  labels:
    app: student-performance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-performance
  template:
    metadata:
      labels:
        app: student-performance
    spec:
      containers:
      - name: student-api
        image: student-performance-api:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20