apiVersion: v1
kind: Service
metadata:
  name: student-performance-service
  namespace: mlops
  labels:
    app: student-performance
spec:
  type: NodePort
  selector:
    app: student-performance
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080